In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [14]:
df = pd.read_csv('finaldetectedfooditems.csv')

In [15]:
df

Name  Calories  FatContent  \
0  Aloo Tikki, Aloo Tikki, Aloo Tikki, Aloo Tikki...    1399.2        18.2   
1                                       French Fries     197.5         0.2   
2                                             Burger     375.0        18.0   
3                       Palak Paneer, Butter Chicken     528.4        32.4   

   SaturatedFatContent  CholesterolContent  SodiumContent  \
0                  3.8                30.0         3560.8   
1                  0.1                 0.0            9.1   
2                  5.0                40.0          900.0   
3                 12.2               116.8          554.8   

   CarbohydrateContent  FiberContent  SugarContent  ProteinContent  foodnumber  
0                261.2          28.8          16.2            41.8           0  
1                 45.7           4.1           2.0             4.2           1  
2                 35.0           2.0           7.0            20.0           2  
3                 30.3          11.6           9.8            36.3           3

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 4 non-null      object 
 1   Calories             4 non-null      float64
 2   FatContent           4 non-null      float64
 3   SaturatedFatContent  4 non-null      float64
 4   CholesterolContent   4 non-null      float64
 5   SodiumContent        4 non-null      float64
 6   CarbohydrateContent  4 non-null      float64
 7   FiberContent         4 non-null      float64
 8   SugarContent         4 non-null      float64
 9   ProteinContent       4 non-null      float64
 10  foodnumber           4 non-null      int64  
dtypes: float64(9), int64(1), object(1)
memory usage: 480.0+ bytes


In [17]:
unique_entries_count = df['Name'].nunique()
unique_entries_count

4

In [18]:
df[df['Name'] == 'Apple']

Empty DataFrame
Columns: [Name, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent, foodnumber]
Index: []

In [19]:
conditions = (df['Calories'] <= 600) & \
             (df['FatContent'] <= 200) & \
             (df['SaturatedFatContent'] <= 45) & \
             (df['CholesterolContent'] <= 100) & \
             (df['SodiumContent'] <= 900) & \
             (df['CarbohydrateContent'] <= 60) & \
             (df['FiberContent'] <= 13) & \
             (df['SugarContent'] <= 12) & \
             (df['ProteinContent'] <= 40)

# Apply conditions to filter out entries
filtered_df = df[conditions]

filtered_df

Name  Calories  FatContent  SaturatedFatContent  \
1  French Fries     197.5         0.2                  0.1   
2        Burger     375.0        18.0                  5.0   

   CholesterolContent  SodiumContent  CarbohydrateContent  FiberContent  \
1                 0.0            9.1                 45.7           4.1   
2                40.0          900.0                 35.0           2.0   

   SugarContent  ProteinContent  foodnumber  
1           2.0             4.2           1  
2           7.0            20.0           2

In [20]:
# Define conditions
conditions = (df['Calories'] <= 600.0) & \
             (df['FatContent'] <= 200.0) & \
             (df['SaturatedFatContent'] <= 45.0) & \
             (df['CholesterolContent'] <= 100.0) & \
             (df['SodiumContent'] <= 900.0) & \
             (df['CarbohydrateContent'] <= 60.0) & \
             (df['FiberContent'] <= 13.0) & \
             (df['SugarContent'] <= 12.0) & \
             (df['ProteinContent'] <= 40.0)

# Create a new column and assign labels based on conditions
df['recommended'] = [0 if condition else 1 for condition in conditions]

In [21]:
df

Name  Calories  FatContent  \
0  Aloo Tikki, Aloo Tikki, Aloo Tikki, Aloo Tikki...    1399.2        18.2   
1                                       French Fries     197.5         0.2   
2                                             Burger     375.0        18.0   
3                       Palak Paneer, Butter Chicken     528.4        32.4   

   SaturatedFatContent  CholesterolContent  SodiumContent  \
0                  3.8                30.0         3560.8   
1                  0.1                 0.0            9.1   
2                  5.0                40.0          900.0   
3                 12.2               116.8          554.8   

   CarbohydrateContent  FiberContent  SugarContent  ProteinContent  \
0                261.2          28.8          16.2            41.8   
1                 45.7           4.1           2.0             4.2   
2                 35.0           2.0           7.0            20.0   
3                 30.3          11.6           9.8            36.3   

   foodnumber  recommended  
0           0            1  
1           1            0  
2           2            0  
3           3            1

In [10]:
#df.to_csv("recommended.csv", index=False)

In [11]:
df=pd.read_csv('recommended.csv')

In [22]:
df['recommended'] = [1 if condition else 0 for condition in conditions]

count_recommended = df['recommended'].value_counts().get(1, 0)
count_not_recommended = df['recommended'].value_counts().get(0, 0)

print("Recommended foods:", count_recommended)
print("Not recommended foods:", count_not_recommended)

Recommended foods: 2
Not recommended foods: 2


In [23]:
del df['foodnumber']

In [24]:
pre_final = df.iloc[:,1:]
pre_final

Calories  FatContent  SaturatedFatContent  CholesterolContent  \
0    1399.2        18.2                  3.8                30.0   
1     197.5         0.2                  0.1                 0.0   
2     375.0        18.0                  5.0                40.0   
3     528.4        32.4                 12.2               116.8   

   SodiumContent  CarbohydrateContent  FiberContent  SugarContent  \
0         3560.8                261.2          28.8          16.2   
1            9.1                 45.7           4.1           2.0   
2          900.0                 35.0           2.0           7.0   
3          554.8                 30.3          11.6           9.8   

   ProteinContent  recommended  
0            41.8            0  
1             4.2            1  
2            20.0            1  
3            36.3            0

In [25]:
X = pre_final.drop(['recommended'], axis='columns')
X

Calories  FatContent  SaturatedFatContent  CholesterolContent  \
0    1399.2        18.2                  3.8                30.0   
1     197.5         0.2                  0.1                 0.0   
2     375.0        18.0                  5.0                40.0   
3     528.4        32.4                 12.2               116.8   

   SodiumContent  CarbohydrateContent  FiberContent  SugarContent  \
0         3560.8                261.2          28.8          16.2   
1            9.1                 45.7           4.1           2.0   
2          900.0                 35.0           2.0           7.0   
3          554.8                 30.3          11.6           9.8   

   ProteinContent  
0            41.8  
1             4.2  
2            20.0  
3            36.3

In [26]:
y = pre_final['recommended']
y

0    0
1    1
2    1
3    0
Name: recommended, dtype: int64

In [27]:
df

Name  Calories  FatContent  \
0  Aloo Tikki, Aloo Tikki, Aloo Tikki, Aloo Tikki...    1399.2        18.2   
1                                       French Fries     197.5         0.2   
2                                             Burger     375.0        18.0   
3                       Palak Paneer, Butter Chicken     528.4        32.4   

   SaturatedFatContent  CholesterolContent  SodiumContent  \
0                  3.8                30.0         3560.8   
1                  0.1                 0.0            9.1   
2                  5.0                40.0          900.0   
3                 12.2               116.8          554.8   

   CarbohydrateContent  FiberContent  SugarContent  ProteinContent  \
0                261.2          28.8          16.2            41.8   
1                 45.7           4.1           2.0             4.2   
2                 35.0           2.0           7.0            20.0   
3                 30.3          11.6           9.8            36.3   

   recommended  
0            0  
1            1  
2            1  
3            0

In [28]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_data=scaler.fit_transform(X.to_numpy())
X_data

array([[ 1.67550973,  0.08756447, -0.33621099, -0.38777798,  1.68471421,
         1.72919603,  1.62972469,  1.45250114,  1.10253835],
       [-0.9252718 , -1.48859592, -1.17958772, -1.08438514, -0.91162987,
        -0.48693091, -0.7140424 , -1.31602453, -1.45249659],
       [-0.54111709,  0.07005157, -0.06268341, -0.1555756 , -0.26036908,
        -0.59696598, -0.91331005, -0.34119154, -0.37883829],
       [-0.20912084,  1.33097988,  1.57848211,  1.62773872, -0.51271527,
        -0.64529914, -0.00237223,  0.20471493,  0.72879654]])

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_data,y,test_size=0.2,random_state=101)

In [31]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

SVC()

In [32]:
model.score(X_test,y_test)

0.0

In [33]:
predictions = model.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))

[[0 0]
 [1 0]]


In [35]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



c:\Users\visha\Desktop\dietrecommendation\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\visha\Desktop\dietrecommendation\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\visha\Desktop\dietrecommendation\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is"

In [36]:
from sklearn.model_selection import GridSearchCV 
param_grid = {'C': [0.1,1,10,100,1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}

In [37]:

grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.

In [90]:
grid.best_params_

{'C': 1, 'gamma': 1}

In [91]:
grid_predictions = grid.predict(X_test)

In [92]:
print(confusion_matrix(y_test,grid_predictions))

[[12  0]
 [ 0 18]]


In [93]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        18

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [94]:
sample_input = {
    'Calories': [300],
    'FatContent': [15],
    'SaturatedFatContent': [5],
    'CholesterolContent': [20],
    'SodiumContent': [500],
    'CarbohydrateContent': [35],
    'FiberContent': [3],
    'SugarContent': [10],
    'ProteinContent': [20],
}

sample_df = pd.DataFrame(sample_input)

test_sample = grid.predict(sample_df)
print(test_sample)

[0]


c:\Users\visha\Desktop\dietrecommendation\env\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(
